import type { CaseEditDraft } from "@/schemas/case-edit.schema";
import type { AutomotiveCaseDetail } from "@/sources/source-detail-repository";

export function createCaseEditDraft(
  automotiveCase: AutomotiveCaseDetail,
): CaseEditDraft {
  return {
    analysisSummary: automotiveCase.analysisSummary,
    caseId: automotiveCase.id,
    caseType: automotiveCase.caseType,
    causes: automotiveCase.causes.map((item) => ({
      description: item.description,
      id: item.id,
      name: item.name,
      nodeId: item.nodeId,
      probabilitySource: item.probabilitySource,
    })),
    complaint: automotiveCase.complaint,
    components: automotiveCase.components.map((item) => ({
      componentType: item.componentType,
      id: item.id,
      name: item.name,
      nodeId: item.nodeId,
      role: item.role,
    })),
    diagnosticChecks: automotiveCase.diagnosticChecks.map((item) => ({
      actualResult: item.actualResult,
      description: item.description,
      expectedResult: item.expectedResult,
      id: item.id,
      interpretation: item.interpretation,
      measurements: item.measurements.map((measurement) => ({
        conditions: measurement.conditions,
        id: measurement.id,
        maxValue: measurement.maxValue,
        minValue: measurement.minValue,
        numericValue: measurement.numericValue,
        parameter: measurement.parameter,
        unit: measurement.unit,
        valueText: measurement.valueText,
      })),
      sequenceOrder: item.sequenceOrder,
    })),
    dtcs: automotiveCase.dtcs.map((item) => ({
      code: item.code,
      description: item.description,
      id: item.id,
      isPrimary: item.isPrimary,
      nodeId: item.nodeId,
      relationshipType: item.relationshipType as CaseEditDraft["dtcs"][number]["relationshipType"],
    })),
    evidence: automotiveCase.evidence.map((item) => ({
      entityId: item.entityId,
      entityType: item.entityType,
      evidenceType: item.evidenceType as CaseEditDraft["evidence"][number]["evidenceType"],
      excerpt: item.excerpt,
      id: item.id,
      pageNumber: item.pageNumber,
    })),
    partsMaterials: automotiveCase.partsMaterials.map((item) => ({
      id: item.id,
      manufacturer: item.manufacturer,
      name: item.name,
      notes: item.notes,
      partNumber: item.partNumber,
    })),
    problemDescription: automotiveCase.problemDescription,
    relationships: automotiveCase.relationships.map((item) => ({
      fromId: item.fromId,
      fromType: item.fromType as CaseEditDraft["relationships"][number]["fromType"],
      id: item.id,
      relationshipType: item.relationshipType,
      sourceEvidenceId: item.sourceEvidenceId,
      toId: item.toId,
      toType: item.toType as CaseEditDraft["relationships"][number]["toType"],
    })),
    reviewNotes: automotiveCase.reviewNotes,
    solutions: automotiveCase.solutions.map((item) => ({
      description: item.description,
      id: item.id,
      name: item.name,
      nodeId: item.nodeId,
      outcomes: item.outcomes,
      probabilitySource: item.probabilitySource,
      procedures: item.procedures.map((procedure) => ({
        id: procedure.id,
        instruction: procedure.instruction,
        sequenceOrder: procedure.sequenceOrder,
      })),
      repairConfirmed: item.repairConfirmed,
      repairSuccessful: item.repairSuccessful,
    })),
    symptoms: automotiveCase.symptoms.map((item) => ({
      description: item.description,
      id: item.id,
      name: item.name,
      nodeId: item.nodeId,
    })),
    title: automotiveCase.title,
    updatedAt: automotiveCase.updatedAt,
    vehicles: automotiveCase.vehicles.map((item) => ({
      brand: item.brand,
      compatibilityNote: item.compatibilityNote,
      engineCode: item.engineCode,
      engineDescription: item.engineDescription,
      fuelType: item.fuelType,
      generation: item.generation,
      id: item.id,
      model: item.model,
      power: item.power,
      transmission: item.transmission,
      yearFrom: item.yearFrom,
      yearTo: item.yearTo,
    })),
  };
}
